### ISSUE TITLE
Other BiRefNet models?

### ISSUE THREAD

**Issue by antithing** [lbq779660843/BiRefNet-Tensorrt#1]
Hi, and thank you very much for this code. 

Would this work the same with all the models in the model zoo from birefnet?
Specifically I am looking at the portrait model.

Thanks!

..also, a problem:

when i run `python pth2onnx.py`

I get this error:

```
C:\BiRefNet\BiRefNet>python pth2onnx.py
Traceback (most recent call last):
  File "C:\BiRefNet\BiRefNet\pth2onnx.py", line 3, in <module>
    from models.birefnet import BiRefNet
  File "C:\BiRefNet\BiRefNet\models\birefnet.py", line 17, in <module>
    class BiRefNet(
TypeError: BiRefNet.__init_subclass__() takes no keyword arguments
```

I have copied your python to the root of BiRefNet. What am i doing wrong?

**Comment by lbq779660843** [comment]
I didn't add these BiRefNet associated python libs, so you should copy both 'pth2onnx.py' and 'deform_conv2d_onnx_exporter.py' into the BiRefNet root path then run it at there.
